### ISSUE TITLE
Hard dependency on ZF1

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/ZF1-Bridge#7]
Currently ```composer.json``` contains:

```
"zendframework/zendframework1": "1.12.*"
```

This seems obvious for this bridge, but we are using the component based / optimized packages from https://github.com/zf1. This way we do not need to download the complete ZF1 and can gradually phase out the use of ZF1 packages and migrate to ZF2. 

Would it be an option to 'suggest' the complete Zend Framework and only  'require' the ```https://github.com/zf1/zend-controller``` ?

**Comment by mnapoli** [comment]
Ah I see. I don't think requiring `https://github.com/zf1/zend-controller` would be a good solution either because some people need the whole package.

The only solution would be indeed to suggest the packages (full ZF1 and zend-controller). This will be a new major release (3.0) as it breaks BC. Do you want to do a pull request?

**Comment by holtkamp** [comment]
Resolved with https://github.com/PHP-DI/ZF1-Bridge/commit/6d102807ce99db7db3e3d6f1363d0bdcfe2d594e

Closing issue
